image: haskell:7.10.3

before_script:
    - apt-get update -y && apt-get install -y -qq git-core dh-autoreconf pkg-config libgtk-3-dev haskell-cairo

stack_job:
  cache:
    untracked: true
    paths:
      - .stack-work
      - ___restore
  script:
    - mkdir -p `pwd`/___restore
    - ln -s `pwd`/___restore /root/.stack
    - stack --no-terminal test rscoin
